export const boldClassicTokens = {
  typography: {
    fontPrimary: 'font-sans',
    fontSecondary: 'font-sans',
    scale: {
      h1: 'text-7xl md:text-9xl',
      h2: 'text-5xl md:text-7xl',
      h2_alt: 'text-4xl md:text-6xl',
      h3: 'text-2xl md:text-3xl',
      h4: 'text-lg',
      h4_xs: 'text-sm',
      bodyLarge: 'text-2xl',
      bodyLarge_alt: 'text-xl',
      body: 'text-lg',
      bodySmall: 'text-base',
      xs: 'text-sm',
      xs_alt: 'text-xs',
    },
    weights: {
      black: 'font-black',
      extrabold: 'font-extrabold',
      bold: 'font-bold',
      semibold: 'font-semibold',
      medium: 'font-medium',
      normal: 'font-normal',
    },
    tracking: {
      tighter: 'tracking-tighter',
      tight: 'tracking-tight',
      normal: 'tracking-normal',
      wide: 'tracking-wide',
      widest: 'tracking-widest',
    },
    lineHeights: {
      none: 'leading-none',
      tight: 'leading-tight',
      snug: 'leading-snug',
      normal: 'leading-normal',
      relaxed: 'leading-relaxed',
      loose: 'leading-loose',
    },
    transform: {
      uppercase: 'uppercase',
      capitalize: 'capitalize',
      none: 'normal-case',
    }
  },
  colors: {
    primary: 'emerald-500',
    primaryHover: 'emerald-600',
    primaryLight: 'emerald-50',
    primaryDim: 'emerald-500/10',
    secondary: 'amber-500',
    secondaryHover: 'amber-600',
    background: 'white',
    surface: 'slate-900',
    surfaceAlt: 'slate-800',
    textPrimary: 'slate-900',
    textMuted: 'slate-600',
    textSubtle: 'slate-400',
    textInverse: 'white',
    textInverseMuted: 'slate-300',
    border: 'slate-200',
    borderLight: 'slate-100',
    heroHeadlinePre: '#FFFFFF',
    sectionHeadlineNormal: '#0F172A',
    sectionHeadlineHighlight: '#10B981',
  },
  layout: {
    container: 'mx-auto',
    containerWidth: 'max-w-[1400px]',
    sectionPaddingLarge: 'py-32',
    sectionPaddingMedium: 'py-24',
    sectionPaddingSmall: 'py-16',
    horizontalPadding: 'px-6 md:px-12 lg:px-16',
    gridGapLarge: 'gap-24',
    gridGapMedium: 'gap-12',
    gridGapSmall: 'gap-8',
    borderRadiusLarge: 'rounded-none',
    borderRadiusMedium: 'rounded-none',
    borderRadiusSmall: 'rounded-sm',
    borderRadiusBase: 'rounded-none',
    borderRadiusIcon: 'rounded-sm',
    shadow: 'shadow-lg',
    shadowLarge: 'shadow-2xl',
    shadowPrimary: 'shadow-emerald-500/20',
  }
};

export default boldClassicTokens;
