export const elegantClassicTokens = {
  typography: {
    fontPrimary: 'font-serif',
    fontSecondary: 'font-sans',
    scale: {
      h1: 'text-6xl md:text-7xl lg:text-8xl',
      h2: 'text-4xl md:text-5xl lg:text-6xl',
      h3: 'text-3xl md:text-4xl',
      h4: 'text-2xl md:text-3xl',
      h5: 'text-xl md:text-2xl',
      body: 'text-base md:text-lg',
      bodyLarge: 'text-lg md:text-xl',
      bodySmall: 'text-sm md:text-base',
      xs: 'text-xs',
    },
    weights: {
      light: 'font-light',
      regular: 'font-normal',
      medium: 'font-medium',
      semibold: 'font-semibold',
      bold: 'font-bold',
    },
    lineHeights: {
      none: 'leading-none',
      tight: 'leading-tight',
      snug: 'leading-snug',
      normal: 'leading-normal',
      relaxed: 'leading-relaxed',
      loose: 'leading-loose',
    },
    tracking: {
      tighter: 'tracking-tighter',
      tight: 'tracking-tight',
      normal: 'tracking-normal',
      wide: 'tracking-wide',
      wider: 'tracking-wider',
      widest: 'tracking-widest',
    },
    transform: {
      uppercase: 'uppercase',
      lowercase: 'lowercase',
      capitalize: 'capitalize',
      none: 'normal-case',
    },
  },

  colors: {
    primary: '#d97706',
    primaryHover: '#b45309',
    accent: '#059669',
    accentHover: '#047857',
    background: '#FFFFFF',
    surface: '#F9FAFB',
    surfaceAlt: '#F3F4F6',
    textPrimary: '#111827',
    textSecondary: '#374151',
    textMuted: '#6B7280',
    textInverse: '#FFFFFF',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    heroPreText: '#d97706',
    heroHeadlineNormal: '#FFFFFF',
    sectionHeadlineNormal: '#111827',
    sectionHeadlineHighlight: '#111827',
  },

  layout: {
    container: 'mx-auto',
    containerWidth: 'max-w-7xl',
    horizontalPadding: 'px-6 md:px-8 lg:px-12',
    sectionPaddingSmall: 'py-12 md:py-16',
    sectionPadding: 'py-16 md:py-20 lg:py-24',
    sectionPaddingLarge: 'py-20 md:py-28 lg:py-32',
    gridGap: 'gap-6 md:gap-8 lg:gap-12',
  },

  spacing: {
    xs: '0.5rem',
    sm: '1rem',
    md: '1.5rem',
    lg: '2rem',
    xl: '3rem',
    '2xl': '4rem',
    '3xl': '6rem',
  },

  borderRadius: {
    none: '0',
    sm: '0.125rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    '2xl': '1rem',
    full: '9999px',
  },
};
