const freshCartTokens = {
  typography: {
    fontPrimary: 'font-sans',
    fontSecondary: 'font-sans',
    scale: {
      h1: 'text-5xl md:text-7xl',
      h2: 'text-4xl md:text-6xl',
      h2_alt: 'text-3xl md:text-5xl',
      h3: 'text-xl',
      h4: 'text-sm',
      h4_xs: 'text-xs',
      bodyLarge: 'text-xl',
      bodyLarge_alt: 'text-lg',
      body: 'text-base',
      bodySmall: 'text-sm',
      xs: 'text-[10px]',
      xs_alt: 'text-xs',
    },
    weights: {
      black: 'font-black',
      extrabold: 'font-extrabold',
      bold: 'font-bold',
      semibold: 'font-semibold',
      medium: 'font-medium',
      normal: 'font-normal',
    },
    tracking: {
      tighter: 'tracking-tight',
      tight: 'tracking-tight',
      normal: 'tracking-normal',
      wide: 'tracking-wide',
      widest: 'tracking-wider',
    },
    lineHeights: {
      none: 'leading-none',
      tight: 'leading-tight',
      snug: 'leading-snug',
      normal: 'leading-normal',
      relaxed: 'leading-relaxed',
      loose: 'leading-loose',
    },
    transform: {
      uppercase: 'uppercase',
      capitalize: 'capitalize',
      none: 'normal-case',
    }
  },
  colors: {
    primary: '#10B981',
    primaryHover: '#059669',
    primaryLight: '#D1FAE5',
    primaryDim: 'rgba(16, 185, 129, 0.1)',
    secondary: '#0EA5E9',
    secondaryHover: '#0284C7',
    background: '#FFFFFF',
    surface: '#F0FDF4',
    surfaceAlt: '#ECFDF5',
    textPrimary: '#064E3B',
    textMuted: '#6B7280',
    textSubtle: '#9CA3AF',
    textInverse: '#FFFFFF',
    textInverseMuted: '#E5E7EB',
    border: '#D1FAE5',
    borderLight: '#F0FDF4',
    accent: '#10B981',
    heroPreText: '#10B981',
    heroHeadlinePre: '#064E3B',
    heroHeadlineNormal: '#064E3B',
    heroHeadlineHighlight: '#10B981',
    sectionHeadlineNormal: '#064E3B',
    sectionHeadlineHighlight: '#10B981',
  },
  layout: {
    container: 'mx-auto',
    containerWidth: 'max-w-7xl',
    sectionPaddingLarge: 'py-20',
    sectionPaddingMedium: 'py-16',
    sectionPaddingSmall: 'py-12',
    horizontalPadding: 'px-6 md:px-12',
    gridGapLarge: 'gap-16',
    gridGapMedium: 'gap-10',
    gridGapSmall: 'gap-6',
    borderRadiusLarge: 'rounded-3xl',
    borderRadiusMedium: 'rounded-2xl',
    borderRadiusSmall: 'rounded-xl',
    borderRadiusBase: 'rounded-lg',
    borderRadiusIcon: 'rounded-xl',
    shadow: 'shadow-sm',
    shadowLarge: 'shadow-xl',
    shadowPrimary: 'shadow-emerald-500/20',
  }
};

export default freshCartTokens;
