export const luxuryClassicTokens = {
  typography: {
    fontPrimary: 'font-serif',
    fontSecondary: 'font-sans',
    scale: {
      h1: 'text-6xl md:text-8xl',
      h2: 'text-4xl md:text-6xl',
      h2_alt: 'text-3xl md:text-5xl',
      h3: 'text-2xl md:text-4xl',
      h4: 'text-xl md:text-2xl',
      h4_xs: 'text-lg',
      bodyLarge: 'text-xl md:text-2xl',
      bodyLarge_alt: 'text-lg md:text-xl',
      body: 'text-base md:text-lg',
      bodySmall: 'text-sm md:text-base',
      xs: 'text-xs',
      xs_alt: 'text-sm',
    },
    weights: {
      black: 'font-black',
      extrabold: 'font-extrabold',
      bold: 'font-bold',
      semibold: 'font-semibold',
      medium: 'font-medium',
      regular: 'font-normal',
      light: 'font-light',
    },
    tracking: {
      tighter: 'tracking-tighter',
      tight: 'tracking-tight',
      normal: 'tracking-normal',
      wide: 'tracking-wide',
      wider: 'tracking-wider',
      widest: 'tracking-widest',
    },
    lineHeights: {
      none: 'leading-none',
      tight: 'leading-tight',
      snug: 'leading-snug',
      normal: 'leading-normal',
      relaxed: 'leading-relaxed',
      loose: 'leading-loose',
    },
    transform: {
      uppercase: 'uppercase',
      capitalize: 'capitalize',
      none: 'normal-case',
    }
  },
  colors: {
    primary: '#D4AF37',
    primaryHover: '#C19B2A',
    primaryLight: '#F5ECD7',
    primaryDim: 'rgba(212, 175, 55, 0.1)',
    secondary: '#1A1A1A',
    secondaryHover: '#2A2A2A',
    background: '#FAFAF8',
    surface: '#1A1A1A',
    surfaceAlt: '#2A2A2A',
    textPrimary: '#1A1A1A',
    textMuted: '#666666',
    textSubtle: '#999999',
    textInverse: '#FFFFFF',
    textInverseMuted: '#CCCCCC',
    border: '#E5E5E5',
    borderLight: '#F0F0F0',
    accent: '#D4AF37',
    heroPreText: '#D4AF37',
    heroHeadlinePre: '#1A1A1A',
    heroHeadlineNormal: '#1A1A1A',
    heroHeadlineHighlight: '#D4AF37',
    sectionHeadlineNormal: '#1A1A1A',
    sectionHeadlineHighlight: '#D4AF37',
  },
  layout: {
    container: 'mx-auto',
    containerWidth: 'max-w-7xl',
    sectionPaddingLarge: 'py-28 md:py-40',
    sectionPaddingMedium: 'py-20 md:py-28',
    sectionPaddingSmall: 'py-14 md:py-20',
    horizontalPadding: 'px-6 md:px-10 lg:px-14',
    gridGapLarge: 'gap-16 md:gap-20',
    gridGapMedium: 'gap-10 md:gap-14',
    gridGapSmall: 'gap-6 md:gap-10',
    borderRadiusLarge: 'rounded-none',
    borderRadiusMedium: 'rounded-none',
    borderRadiusSmall: 'rounded-none',
    borderRadiusBase: 'rounded-none',
    borderRadiusIcon: 'rounded-none',
    shadow: 'shadow-md',
    shadowLarge: 'shadow-2xl shadow-black/10',
    shadowPrimary: 'shadow-xl shadow-amber-500/20',
  }
};

export default luxuryClassicTokens;
