export const luxuryClassicTokens = {
  typography: {
    fontPrimary: 'font-serif',
    fontSecondary: 'font-sans',
    scale: {
      h1: 'text-5xl md:text-7xl',
      h2: 'text-3xl md:text-5xl',
      h2_alt: 'text-4xl md:text-5xl',
      h3: 'text-2xl md:text-3xl',
      h4: 'text-lg md:text-xl',
      h4_xs: 'text-base',
      bodyLarge: 'text-lg md:text-xl',
      bodyLarge_alt: 'text-base md:text-lg',
      body: 'text-base',
      bodySmall: 'text-sm',
      xs: 'text-xs',
      xs_alt: 'text-sm',
    },
    weights: {
      light: 'font-light',
      regular: 'font-normal',
      medium: 'font-medium',
      semibold: 'font-semibold',
      bold: 'font-bold',
    },
    tracking: {
      tighter: 'tracking-tight',
      tight: 'tracking-tight',
      normal: 'tracking-normal',
      wide: 'tracking-wide',
      widest: 'tracking-[0.15em]',
    },
    lineHeights: {
      none: 'leading-none',
      tight: 'leading-tight',
      snug: 'leading-snug',
      normal: 'leading-normal',
      relaxed: 'leading-relaxed',
      loose: 'leading-loose',
    },
    transform: {
      uppercase: 'uppercase',
      capitalize: 'capitalize',
      none: 'normal-case',
    }
  },
  colors: {
    primary: '#D4AF37',
    primaryHover: '#B8941F',
    primaryLight: '#F5ECD7',
    primaryDim: 'rgba(212, 175, 55, 0.1)',
    secondary: '#1A1A1A',
    secondaryHover: '#2D2D2D',
    background: '#0A0A0A',
    surface: '#1A1A1A',
    surfaceAlt: '#2D2D2D',
    textPrimary: '#FFFFFF',
    textMuted: '#A0A0A0',
    textSubtle: '#707070',
    textInverse: '#0A0A0A',
    textInverseMuted: '#1A1A1A',
    border: '#2D2D2D',
    borderLight: '#3D3D3D',
    accent: '#D4AF37',
    heroPreText: '#D4AF37',
    heroHeadlinePre: '#FFFFFF',
    heroHeadlineNormal: '#FFFFFF',
    heroHeadlineHighlight: '#D4AF37',
    sectionHeadlineNormal: '#FFFFFF',
    sectionHeadlineHighlight: '#D4AF37',
  },
  layout: {
    container: 'mx-auto',
    containerWidth: 'max-w-7xl',
    sectionPaddingLarge: 'py-24 md:py-32',
    sectionPaddingMedium: 'py-16 md:py-24',
    sectionPaddingSmall: 'py-12 md:py-16',
    horizontalPadding: 'px-6 md:px-10 lg:px-12',
    gridGapLarge: 'gap-12 md:gap-16',
    gridGapMedium: 'gap-8 md:gap-10',
    gridGapSmall: 'gap-6 md:gap-8',
    borderRadiusLarge: 'rounded-none',
    borderRadiusMedium: 'rounded-none',
    borderRadiusSmall: 'rounded-none',
    borderRadiusBase: 'rounded-none',
    borderRadiusIcon: 'rounded-none',
    shadow: 'shadow-none',
    shadowLarge: 'shadow-2xl shadow-black/50',
    shadowPrimary: 'shadow-lg shadow-amber-500/20',
  }
};

export default luxuryClassicTokens;
