const modernGradientTokens = {
  typography: {
    fontPrimary: 'font-sans',
    fontSecondary: 'font-sans',
    scale: {
      h1: 'text-6xl md:text-8xl',
      h2: 'text-4xl md:text-6xl',
      h2_alt: 'text-3xl md:text-5xl',
      h3: 'text-2xl',
      h4: 'text-sm',
      h4_xs: 'text-xs',
      bodyLarge: 'text-xl',
      bodyLarge_alt: 'text-lg',
      body: 'text-base',
      bodySmall: 'text-sm',
      xs: 'text-[10px]',
      xs_alt: 'text-xs',
    },
    weights: {
      black: 'font-black',
      extrabold: 'font-extrabold',
      bold: 'font-bold',
      semibold: 'font-semibold',
      medium: 'font-medium',
      normal: 'font-normal',
    },
    tracking: {
      tighter: 'tracking-tighter',
      tight: 'tracking-tight',
      normal: 'tracking-normal',
      wide: 'tracking-wide',
      widest: 'tracking-widest',
    },
    lineHeights: {
      none: 'leading-none',
      tight: 'leading-tight',
      snug: 'leading-snug',
      normal: 'leading-normal',
      relaxed: 'leading-relaxed',
      loose: 'leading-loose',
    },
    transform: {
      uppercase: 'uppercase',
      capitalize: 'capitalize',
      none: 'normal-case',
    }
  },
  colors: {
    primary: '#EC4899',
    primaryHover: '#DB2777',
    primaryLight: '#FCE7F3',
    primaryDim: 'rgba(236, 72, 153, 0.15)',
    secondary: '#8B5CF6',
    secondaryHover: '#7C3AED',
    background: '#FFFFFF',
    surface: '#FAFAFA',
    surfaceAlt: '#F5F5F5',
    textPrimary: '#0F172A',
    textMuted: '#64748B',
    textSubtle: '#94A3B8',
    textInverse: '#FFFFFF',
    textInverseMuted: '#E2E8F0',
    border: '#F1F5F9',
    borderLight: '#F8FAFC',
    accent: '#EC4899',
    heroPreText: '#EC4899',
    heroHeadlinePre: '#0F172A',
    heroHeadlineNormal: '#0F172A',
    heroHeadlineHighlight: '#EC4899',
    sectionHeadlineNormal: '#0F172A',
    sectionHeadlineHighlight: '#EC4899',
  },
  layout: {
    container: 'mx-auto',
    containerWidth: 'max-w-7xl',
    sectionPaddingLarge: 'py-28',
    sectionPaddingMedium: 'py-20',
    sectionPaddingSmall: 'py-14',
    horizontalPadding: 'px-6 md:px-12',
    gridGapLarge: 'gap-20',
    gridGapMedium: 'gap-14',
    gridGapSmall: 'gap-8',
    borderRadiusLarge: 'rounded-[48px]',
    borderRadiusMedium: 'rounded-[36px]',
    borderRadiusSmall: 'rounded-[24px]',
    borderRadiusBase: 'rounded-2xl',
    borderRadiusIcon: 'rounded-3xl',
    shadow: 'shadow-lg',
    shadowLarge: 'shadow-2xl',
    shadowPrimary: 'shadow-pink-500/25',
  }
};

export default modernGradientTokens;
