const modernSplitTokens = {
  typography: {
    fontPrimary: 'font-sans',
    fontSecondary: 'font-sans',
    scale: {
      h1: 'text-5xl md:text-6xl lg:text-7xl',
      h2: 'text-3xl md:text-4xl lg:text-5xl',
      h3: 'text-2xl md:text-3xl lg:text-4xl',
      h4: 'text-xl md:text-2xl lg:text-3xl',
      h5: 'text-lg md:text-xl',
      body: 'text-base',
      bodyLarge: 'text-lg',
      bodySmall: 'text-sm',
      xs: 'text-xs',
    },
    weights: {
      light: 'font-light',
      regular: 'font-normal',
      medium: 'font-medium',
      semibold: 'font-semibold',
      bold: 'font-bold',
      extrabold: 'font-extrabold',
    },
    lineHeights: {
      none: 'leading-none',
      tight: 'leading-tight',
      snug: 'leading-snug',
      normal: 'leading-normal',
      relaxed: 'leading-relaxed',
      loose: 'leading-loose',
    },
    tracking: {
      tighter: 'tracking-tighter',
      tight: 'tracking-tight',
      normal: 'tracking-normal',
      wide: 'tracking-wide',
      wider: 'tracking-wider',
      widest: 'tracking-widest',
    },
    transform: {
      uppercase: 'uppercase',
      lowercase: 'lowercase',
      capitalize: 'capitalize',
      none: 'normal-case',
    },
  },

  colors: {
    primary: '#2563eb',
    primaryHover: '#1d4ed8',
    accent: '#f59e0b',
    accentHover: '#d97706',
    background: '#FFFFFF',
    surface: '#F9FAFB',
    surfaceAlt: '#F3F4F6',
    textPrimary: '#111827',
    textSecondary: '#374151',
    textMuted: '#6B7280',
    textInverse: '#FFFFFF',
    textInverseMuted: 'rgba(255, 255, 255, 0.8)',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    heroPreText: '#f59e0b',
    heroHeadlineNormal: '#111827',
    sectionHeadlineNormal: '#111827',
    sectionHeadlineHighlight: '#f59e0b',
    cartBackground: '#FFFFFF',
    cartBorder: '#E5E7EB',
  },

  layout: {
    container: 'mx-auto',
    containerWidth: 'max-w-7xl',
    horizontalPadding: 'px-4 md:px-6 lg:px-8',
    sectionPaddingSmall: 'py-8 md:py-12',
    sectionPadding: 'py-12 md:py-16',
    sectionPaddingLarge: 'py-16 md:py-20',
    gridGap: 'gap-4 md:gap-6',
  },

  spacing: {
    xs: '0.5rem',
    sm: '1rem',
    md: '1.5rem',
    lg: '2rem',
    xl: '3rem',
    '2xl': '4rem',
    '3xl': '6rem',
  },

  borderRadius: {
    none: '0',
    sm: '0.25rem',
    md: '0.5rem',
    lg: '0.75rem',
    xl: '1rem',
    '2xl': '1.5rem',
    full: '9999px',
  },
};

export default modernSplitTokens;
