const modernSplitCartTokens = {
  typography: {
    fontPrimary: 'font-sans',
    fontSecondary: 'font-sans',
    scale: {
      h1: 'text-3xl md:text-4xl lg:text-5xl',
      h2: 'text-2xl md:text-3xl',
      h3: 'text-xl md:text-2xl',
      h4: 'text-lg md:text-xl',
      h5: 'text-base md:text-lg',
      body: 'text-sm',
      bodyLarge: 'text-base',
      bodySmall: 'text-xs',
      xs: 'text-[10px]',
    },
    weights: {
      light: 'font-light',
      regular: 'font-normal',
      medium: 'font-medium',
      semibold: 'font-semibold',
      bold: 'font-bold',
      extrabold: 'font-extrabold',
    },
    lineHeights: {
      none: 'leading-none',
      tight: 'leading-tight',
      snug: 'leading-snug',
      normal: 'leading-normal',
      relaxed: 'leading-relaxed',
      loose: 'leading-loose',
    },
    tracking: {
      tighter: 'tracking-tighter',
      tight: 'tracking-tight',
      normal: 'tracking-normal',
      wide: 'tracking-wide',
      wider: 'tracking-wider',
      widest: 'tracking-widest',
    },
    transform: {
      uppercase: 'uppercase',
      lowercase: 'lowercase',
      capitalize: 'capitalize',
      none: 'normal-case',
    },
  },

  colors: {
    primary: '#2563eb',
    primaryHover: '#1d4ed8',
    accent: '#f97316',
    accentHover: '#ea580c',
    background: '#FFFFFF',
    surface: '#FAFAFA',
    surfaceAlt: '#F5F5F5',
    textPrimary: '#0A0A0A',
    textSecondary: '#525252',
    textMuted: '#737373',
    textInverse: '#FFFFFF',
    textInverseMuted: 'rgba(255, 255, 255, 0.8)',
    border: '#E5E5E5',
    borderLight: '#F5F5F5',
    heroPreText: '#f97316',
    heroHeadlineNormal: '#0A0A0A',
    sectionHeadlineNormal: '#0A0A0A',
    sectionHeadlineHighlight: '#f97316',
    cartBackground: '#FFFFFF',
    cartBorder: '#E5E5E5',
  },

  layout: {
    container: 'mx-auto',
    containerWidth: 'max-w-7xl',
    horizontalPadding: 'px-4 md:px-5 lg:px-6',
    sectionPaddingSmall: 'py-4 md:py-6',
    sectionPadding: 'py-6 md:py-8',
    sectionPaddingLarge: 'py-8 md:py-10',
    gridGap: 'gap-3 md:gap-4',
  },

  spacing: {
    xs: '0.375rem',
    sm: '0.75rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    '2xl': '2.5rem',
    '3xl': '3rem',
  },

  borderRadius: {
    none: '0',
    sm: '0.25rem',
    md: '0.5rem',
    lg: '0.75rem',
    xl: '1rem',
    '2xl': '1.25rem',
    full: '9999px',
  },
};

export default modernSplitCartTokens;
