export const modernClassicTokens = {
  typography: {
    fontPrimary: 'font-sans',
    fontSecondary: 'font-sans',
    scale: {
      h1: 'text-6xl md:text-8xl',
      h2: 'text-3xl md:text-5xl',
      h2_alt: 'text-4xl md:text-6xl',
      h3: 'text-2xl',
      h4: 'text-base',
      h4_xs: 'text-xs',
      bodyLarge: 'text-xl',
      bodyLarge_alt: 'text-lg',
      body: 'text-base',
      bodySmall: 'text-sm',
      xs: 'text-xs',
      xs_alt: 'text-sm',
    },
    weights: {
      black: 'font-black',
      extrabold: 'font-extrabold',
      bold: 'font-bold',
      semibold: 'font-semibold',
      medium: 'font-medium',
      normal: 'font-normal',
    },
    tracking: {
      tighter: 'tracking-tighter',
      tight: 'tracking-tight',
      normal: 'tracking-normal',
      wide: 'tracking-wide',
      widest: 'tracking-wider',
    },
    lineHeights: {
      none: 'leading-none',
      tight: 'leading-tight',
      snug: 'leading-snug',
      normal: 'leading-normal',
      relaxed: 'leading-relaxed',
      loose: 'leading-loose',
    },
    transform: {
      uppercase: 'uppercase',
      capitalize: 'capitalize',
      none: 'normal-case',
    }
  },
  colors: {
    primary: 'blue-600',
    primaryHover: 'blue-700',
    primaryLight: 'blue-50',
    primaryDim: 'blue-600/10',
    secondary: 'gray-900',
    secondaryHover: 'gray-800',
    background: 'white',
    surface: 'gray-50',
    surfaceAlt: 'gray-100',
    textPrimary: 'gray-900',
    textMuted: 'gray-600',
    textSubtle: 'gray-400',
    textInverse: 'white',
    textInverseMuted: 'gray-200',
    border: 'gray-200',
    borderLight: 'gray-100',
    heroHeadlinePre: '#FFFFFF',
    sectionHeadlineNormal: '#1F2937',
    sectionHeadlineHighlight: '#1F2937',
  },
  layout: {
    container: 'mx-auto',
    containerWidth: 'max-w-6xl',
    sectionPaddingLarge: 'py-20',
    sectionPaddingMedium: 'py-16',
    sectionPaddingSmall: 'py-12',
    horizontalPadding: 'px-6 md:px-8',
    gridGapLarge: 'gap-16',
    gridGapMedium: 'gap-8',
    gridGapSmall: 'gap-6',
    borderRadiusLarge: 'rounded-3xl',
    borderRadiusMedium: 'rounded-2xl',
    borderRadiusSmall: 'rounded-xl',
    borderRadiusBase: 'rounded-lg',
    borderRadiusIcon: 'rounded-xl',
    shadow: 'shadow-sm',
    shadowLarge: 'shadow-xl',
    shadowPrimary: 'shadow-blue-600/10',
  }
};

export default modernClassicTokens;
