export const refinedClassicTokens = {
  typography: {
    fontPrimary: 'font-sans',
    fontSecondary: 'font-sans',
    scale: {
      h1: 'text-5xl md:text-7xl',
      h2: 'text-3xl md:text-5xl',
      h2_alt: 'text-4xl md:text-6xl',
      h3: 'text-2xl md:text-3xl',
      h4: 'text-lg md:text-xl',
      h4_xs: 'text-base',
      bodyLarge: 'text-lg md:text-xl',
      bodyLarge_alt: 'text-base md:text-lg',
      body: 'text-base',
      bodySmall: 'text-sm',
      xs: 'text-xs',
      xs_alt: 'text-sm',
    },
    weights: {
      bold: 'font-bold',
      semibold: 'font-semibold',
      medium: 'font-medium',
      normal: 'font-normal',
      light: 'font-light',
    },
    tracking: {
      tighter: 'tracking-tight',
      tight: 'tracking-tight',
      normal: 'tracking-normal',
      wide: 'tracking-wide',
      widest: 'tracking-wider',
    },
    lineHeights: {
      none: 'leading-none',
      tight: 'leading-tight',
      snug: 'leading-snug',
      normal: 'leading-normal',
      relaxed: 'leading-relaxed',
      loose: 'leading-loose',
    },
    transform: {
      uppercase: 'uppercase',
      capitalize: 'capitalize',
      none: 'normal-case',
    }
  },
  colors: {
    primary: '#0891B2',
    primaryHover: '#0E7490',
    primaryLight: '#ECFEFF',
    primaryDim: 'rgba(8, 145, 178, 0.1)',
    secondary: '#0F172A',
    secondaryHover: '#1E293B',
    background: '#FFFFFF',
    surface: '#F8FAFC',
    surfaceAlt: '#F1F5F9',
    textPrimary: '#0F172A',
    textMuted: '#475569',
    textSubtle: '#94A3B8',
    textInverse: '#FFFFFF',
    textInverseMuted: '#E2E8F0',
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
    accent: '#0891B2',
    heroPreText: '#0891B2',
    heroHeadlinePre: '#FFFFFF',
    heroHeadlineNormal: '#0F172A',
    heroHeadlineHighlight: '#0891B2',
    sectionHeadlineNormal: '#0F172A',
    sectionHeadlineHighlight: '#0891B2',
  },
  layout: {
    container: 'mx-auto',
    containerWidth: 'max-w-6xl',
    sectionPaddingLarge: 'py-24 md:py-32',
    sectionPaddingMedium: 'py-16 md:py-24',
    sectionPaddingSmall: 'py-12 md:py-16',
    horizontalPadding: 'px-6 md:px-8 lg:px-10',
    gridGapLarge: 'gap-12 md:gap-16',
    gridGapMedium: 'gap-8 md:gap-12',
    gridGapSmall: 'gap-6 md:gap-8',
    borderRadiusLarge: 'rounded-2xl',
    borderRadiusMedium: 'rounded-xl',
    borderRadiusSmall: 'rounded-lg',
    borderRadiusBase: 'rounded-lg',
    borderRadiusIcon: 'rounded-lg',
    shadow: 'shadow-sm',
    shadowLarge: 'shadow-xl shadow-cyan-500/10',
    shadowPrimary: 'shadow-lg shadow-cyan-500/15',
  }
};

export default refinedClassicTokens;
