export const vibrantClassicTokens = {
  typography: {
    fontPrimary: 'font-sans',
    fontSecondary: 'font-sans',
    scale: {
      h1: 'text-6xl md:text-8xl',
      h2: 'text-4xl md:text-6xl',
      h2_alt: 'text-3xl md:text-5xl',
      h3: 'text-2xl md:text-4xl',
      h4: 'text-xl md:text-2xl',
      h4_xs: 'text-lg',
      bodyLarge: 'text-xl md:text-2xl',
      bodyLarge_alt: 'text-lg md:text-xl',
      body: 'text-base md:text-lg',
      bodySmall: 'text-sm md:text-base',
      xs: 'text-xs',
      xs_alt: 'text-sm',
    },
    weights: {
      black: 'font-black',
      extrabold: 'font-extrabold',
      bold: 'font-bold',
      semibold: 'font-semibold',
      medium: 'font-medium',
      regular: 'font-normal',
    },
    tracking: {
      tighter: 'tracking-tighter',
      tight: 'tracking-tight',
      normal: 'tracking-normal',
      wide: 'tracking-wide',
      wider: 'tracking-wider',
      widest: 'tracking-widest',
    },
    lineHeights: {
      none: 'leading-none',
      tight: 'leading-tight',
      snug: 'leading-snug',
      normal: 'leading-normal',
      relaxed: 'leading-relaxed',
      loose: 'leading-loose',
    },
    transform: {
      uppercase: 'uppercase',
      capitalize: 'capitalize',
      none: 'normal-case',
    }
  },
  colors: {
    primary: '#EC4899',
    primaryHover: '#DB2777',
    primaryLight: '#FCE7F3',
    primaryDim: 'rgba(236, 72, 153, 0.1)',
    secondary: '#8B5CF6',
    secondaryHover: '#7C3AED',
    background: '#FFFFFF',
    surface: '#F9FAFB',
    surfaceAlt: '#F3F4F6',
    textPrimary: '#111827',
    textMuted: '#6B7280',
    textSubtle: '#9CA3AF',
    textInverse: '#FFFFFF',
    textInverseMuted: '#E5E7EB',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    accent: '#F59E0B',
    heroPreText: '#EC4899',
    heroHeadlinePre: '#111827',
    heroHeadlineNormal: '#111827',
    heroHeadlineHighlight: '#EC4899',
    sectionHeadlineNormal: '#111827',
    sectionHeadlineHighlight: '#EC4899',
  },
  layout: {
    container: 'mx-auto',
    containerWidth: 'max-w-7xl',
    sectionPaddingLarge: 'py-24 md:py-36',
    sectionPaddingMedium: 'py-16 md:py-24',
    sectionPaddingSmall: 'py-12 md:py-16',
    horizontalPadding: 'px-6 md:px-10 lg:px-12',
    gridGapLarge: 'gap-12 md:gap-16',
    gridGapMedium: 'gap-8 md:gap-12',
    gridGapSmall: 'gap-6 md:gap-8',
    borderRadiusLarge: 'rounded-3xl',
    borderRadiusMedium: 'rounded-2xl',
    borderRadiusSmall: 'rounded-xl',
    borderRadiusBase: 'rounded-xl',
    borderRadiusIcon: 'rounded-2xl',
    shadow: 'shadow-md',
    shadowLarge: 'shadow-2xl',
    shadowPrimary: 'shadow-xl shadow-pink-500/20',
  }
};

export default vibrantClassicTokens;
