export const vibrantClassicTokens = {
  typography: {
    fontPrimary: 'font-sans',
    fontSecondary: 'font-sans',
    scale: {
      h1: 'text-6xl md:text-8xl',
      h2: 'text-4xl md:text-6xl',
      h2_alt: 'text-3xl md:text-5xl',
      h3: 'text-2xl md:text-4xl',
      h4: 'text-xl md:text-2xl',
      h4_xs: 'text-lg',
      bodyLarge: 'text-xl md:text-2xl',
      bodyLarge_alt: 'text-lg md:text-xl',
      body: 'text-base md:text-lg',
      bodySmall: 'text-sm md:text-base',
      xs: 'text-xs',
      xs_alt: 'text-sm',
    },
    weights: {
      black: 'font-black',
      extrabold: 'font-extrabold',
      bold: 'font-bold',
      semibold: 'font-semibold',
      medium: 'font-medium',
      normal: 'font-normal',
    },
    tracking: {
      tighter: 'tracking-tight',
      tight: 'tracking-tight',
      normal: 'tracking-normal',
      wide: 'tracking-wide',
      widest: 'tracking-wider',
    },
    lineHeights: {
      none: 'leading-none',
      tight: 'leading-tight',
      snug: 'leading-snug',
      normal: 'leading-normal',
      relaxed: 'leading-relaxed',
      loose: 'leading-loose',
    },
    transform: {
      uppercase: 'uppercase',
      capitalize: 'capitalize',
      none: 'normal-case',
    }
  },
  colors: {
    primary: '#EC4899',
    primaryHover: '#DB2777',
    primaryLight: '#FCE7F3',
    primaryDim: 'rgba(236, 72, 153, 0.1)',
    secondary: '#8B5CF6',
    secondaryHover: '#7C3AED',
    background: '#FFFFFF',
    surface: '#FAFAFA',
    surfaceAlt: '#F5F5F5',
    textPrimary: '#0F172A',
    textMuted: '#475569',
    textSubtle: '#94A3B8',
    textInverse: '#FFFFFF',
    textInverseMuted: '#F1F5F9',
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
    accent: '#F59E0B',
    heroPreText: '#EC4899',
    heroHeadlinePre: '#FFFFFF',
    heroHeadlineNormal: '#0F172A',
    heroHeadlineHighlight: '#EC4899',
    sectionHeadlineNormal: '#0F172A',
    sectionHeadlineHighlight: '#8B5CF6',
  },
  layout: {
    container: 'mx-auto',
    containerWidth: 'max-w-7xl',
    sectionPaddingLarge: 'py-20 md:py-28',
    sectionPaddingMedium: 'py-16 md:py-20',
    sectionPaddingSmall: 'py-12 md:py-16',
    horizontalPadding: 'px-6 md:px-8 lg:px-12',
    gridGapLarge: 'gap-16 md:gap-20',
    gridGapMedium: 'gap-10 md:gap-12',
    gridGapSmall: 'gap-6 md:gap-8',
    borderRadiusLarge: 'rounded-[32px]',
    borderRadiusMedium: 'rounded-3xl',
    borderRadiusSmall: 'rounded-2xl',
    borderRadiusBase: 'rounded-xl',
    borderRadiusIcon: 'rounded-2xl',
    shadow: 'shadow-lg shadow-pink-500/10',
    shadowLarge: 'shadow-2xl shadow-pink-500/20',
    shadowPrimary: 'shadow-xl shadow-pink-500/25',
  }
};

export default vibrantClassicTokens;
