const warmCulinaryTokens = {
  typography: {
    fontPrimary: 'font-serif',
    fontSecondary: 'font-sans',
    scale: {
      h1: 'text-4xl md:text-5xl lg:text-6xl',
      h2: 'text-3xl md:text-4xl lg:text-5xl',
      h3: 'text-2xl md:text-3xl lg:text-4xl',
      h4: 'text-xl md:text-2xl lg:text-3xl',
      h5: 'text-lg md:text-xl',
      body: 'text-base',
      bodyLarge: 'text-lg',
      bodySmall: 'text-sm',
      xs: 'text-xs',
    },
    weights: {
      light: 'font-light',
      regular: 'font-normal',
      medium: 'font-medium',
      semibold: 'font-semibold',
      bold: 'font-bold',
      extrabold: 'font-extrabold',
    },
    lineHeights: {
      none: 'leading-none',
      tight: 'leading-tight',
      snug: 'leading-snug',
      normal: 'leading-normal',
      relaxed: 'leading-relaxed',
      loose: 'leading-loose',
    },
    tracking: {
      tighter: 'tracking-tighter',
      tight: 'tracking-tight',
      normal: 'tracking-normal',
      wide: 'tracking-wide',
      wider: 'tracking-wider',
      widest: 'tracking-widest',
    },
    transform: {
      uppercase: 'uppercase',
      lowercase: 'lowercase',
      capitalize: 'capitalize',
      none: 'normal-case',
    },
  },

  colors: {
    primary: '#D4A574',
    primaryHover: '#C49563',
    accent: '#E8B870',
    accentHover: '#D4A574',
    background: '#FAF8F5',
    surface: '#FFFFFF',
    surfaceAlt: '#F5F1EB',
    textPrimary: '#1A1A1A',
    textSecondary: '#4A4A4A',
    textMuted: '#7A7A7A',
    textInverse: '#FFFFFF',
    textInverseMuted: 'rgba(255, 255, 255, 0.85)',
    border: '#E8E4DD',
    borderLight: '#F0EDE7',
    heroPreText: '#D4A574',
    heroHeadlineNormal: '#1A1A1A',
    sectionHeadlineNormal: '#1A1A1A',
    sectionHeadlineHighlight: '#D4A574',
    cardBackground: '#FFFFFF',
    cardShadow: 'rgba(0, 0, 0, 0.08)',
  },

  layout: {
    container: 'mx-auto',
    containerWidth: 'max-w-7xl',
    horizontalPadding: 'px-6 md:px-8 lg:px-12',
    sectionPaddingSmall: 'py-12 md:py-16',
    sectionPadding: 'py-16 md:py-20',
    sectionPaddingLarge: 'py-20 md:py-24',
    gridGap: 'gap-6 md:gap-8',
  },

  spacing: {
    xs: '0.5rem',
    sm: '1rem',
    md: '1.5rem',
    lg: '2rem',
    xl: '3rem',
    '2xl': '4rem',
    '3xl': '6rem',
  },

  borderRadius: {
    none: '0',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.25rem',
    xl: '1.5rem',
    '2xl': '2rem',
    '3xl': '2.5rem',
    full: '9999px',
  },
};

export default warmCulinaryTokens;
